#!/bin/sh

set -e -x

go get github.com/vito/gosub
go get github.com/sparrc/gdm

REPO=$(cd $(dirname $0)/.. && pwd)
export GOPATH=$REPO/src/influxdb

# for gosub to be able to bootstrap
touch $REPO/.gitmodules

# so we can start from scratch
go get -d -v github.com/influxdata/influxdb/cmd/influxd
go get -d -v github.com/influxdata/influxdb/cmd/influx

# set dependency versions with gdm
cd $GOPATH/src/github.com/influxdata/influxdb
git checkout v0.13.0
gdm restore

# sync errything
( gosub list -a github.com/influxdata/influxdb/cmd/influxd && \
  gosub list -a github.com/influxdata/influxdb/cmd/influx ) | \
  xargs gosub sync -r $REPO -g $GOPATH
